version: "3.7"

services:
  app:
    build: .
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - WAIT_HOSTS=db:5432
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
    command: sh -c "npm install && /wait && npm run migrate && npm start"

  db:
    image: postgres:13-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
